# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'macOS-10.13' # ubuntu-latest

variables:
  buildConfiguration: 'Release'

#steps:
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
   command: build
   projects: '**/*.csproj'
   arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
   command: test
   projects: '**/*Tests/*.csproj'
   arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
   command: publish
   publishWebProjects: True
   arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
   zipAfterPublish: true
- task: PublishBuildArtifacts@1
  displayName: PublishBuildArtifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'myWebSiteName'


